<<<<<<< HEAD
name: app_corrida
=======
name: app02
>>>>>>> 54ee9696c6c4b0b149e186b172ed1e6f6cbe7083
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.3.1
<<<<<<< HEAD
  get_it: ^8.2.0
=======
>>>>>>> 54ee9696c6c4b0b149e186b172ed1e6f6cbe7083

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
